# Percy configuration for production-ready setup
version: 2
snapshot:
  widths: [375, 768, 1280]
  min-height: 1024
  percy-css: |
    /* Hide dynamic content that might cause flaky tests */
    [data-testid="timestamp"],
    .animate-spin,
    .animate-pulse {
      display: none !important;
    }
    /* Disable animations for consistent snapshots */
    *, *::before, *::after {
      animation-duration: 0s !important;
      animation-delay: 0s !important;
      transition-duration: 0s !important;
      transition-delay: 0s !important;
    }
discovery:
  # Allow Percy to wait for network requests and animations
  request-headers:
    User-Agent: Percy
  # Network idle timeout - wait for all network requests to complete
  network-idle-timeout: 750
  # Allow more time for page to stabilize
  wait-for-timeout: 2000
